const { getDefaultConfig } = require('expo/metro-config');
const path = require('path');

// Find the project root directory
const projectRoot = __dirname;
// Find the workspace root directory (up two levels)
const workspaceRoot = path.resolve(projectRoot, '../..');

const config = getDefaultConfig(projectRoot);

// 1. Watch all files in the monorepo workspace root
config.watchFolders = [workspaceRoot];

// 2. Let Metro search node_modules folders inside the workspace
config.resolver.nodeModulesPaths = [
  path.resolve(projectRoot, 'node_modules'),
  path.resolve(workspaceRoot, 'node_modules'),
];

// 3. Force Metro to resolve physical symlinks generated by your package manager
config.resolver.disableHierarchicalLookup = true;

module.exports = config;
